services:
  app:
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
    depends_on:
      - db

  webserver:
    ports:
      - "8000:80"

  db:
    image: mysql:8.0
    container_name: itcc-db
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - itcc-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      interval: 1m
      timeout: 30s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:latest
    platform: linux/amd64
    container_name: itcc-pma
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PMA_HOST: ${DB_HOST:-db}
      PMA_PORT: ${DB_PORT:-3306}
      PMA_USER: ${DB_USERNAME:-root}
      PMA_PASSWORD: ${DB_PASSWORD:-root}
    restart: always
    ports:
      - "8080:80"
    networks:
      - itcc-network

volumes:
  dbdata:
    driver: local
