version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: itcc-website
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/app.ini
    env_file:
      - .env
    networks:
      - itcc-network
    command: sh -c "php-fpm"

  webserver:
    image: nginx:alpine
    container_name: itcc-webserver
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - itcc-network

networks:
  itcc-network:
    driver: bridge
